import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "TokenTopNews Privacy Policy — how we collect, use, and protect your data.",
};

const SECTIONS = [
  {
    title: "1. Information We Collect",
    body: "We collect information you provide directly (name, email, payment details), information generated by your use of the Service (pages viewed, articles read, alerts created), and technical data (IP address, browser type, device identifiers).",
  },
  {
    title: "2. How We Use Your Information",
    body: "We use your information to provide and improve the Service, process payments, send newsletters and alerts you have subscribed to, and comply with legal obligations. We do not sell your personal data.",
  },
  {
    title: "3. Cookies",
    body: "We use essential cookies to operate the Service and optional analytics cookies to understand usage patterns. You can manage cookie preferences at any time. See our Cookie Policy for details.",
  },
  {
    title: "4. Data Sharing",
    body: "We share data only with service providers necessary to operate the platform (payment processors, email delivery, analytics). All third parties are contractually bound to protect your data.",
  },
  {
    title: "5. Data Retention",
    body: "We retain account data for as long as your account is active. You may request deletion of your data at any time by contacting privacy@tokentopnews.com.",
  },
  {
    title: "6. Your Rights",
    body: "Depending on your jurisdiction, you may have rights to access, correct, delete, or export your personal data. Submit requests to privacy@tokentopnews.com. We respond within 30 days.",
  },
  {
    title: "7. Security",
    body: "We use industry-standard encryption and access controls to protect your data. TokenTopNews is SOC 2 Type II certified. Despite our efforts, no system is 100% secure.",
  },
  {
    title: "8. Children",
    body: "The Service is not directed at children under 16. We do not knowingly collect data from anyone under 16. If you believe we have done so inadvertently, contact us for immediate deletion.",
  },
  {
    title: "9. Changes",
    body: "We may update this Privacy Policy periodically. We will notify you of material changes via email or a prominent notice on the Service.",
  },
  {
    title: "10. Contact",
    body: "Privacy questions or requests: privacy@tokentopnews.com",
  },
];

export default function PrivacyPage() {
  return (
    <main>
      <section
        style={{
          background: "var(--surface)",
          borderBottom: "0.5px solid var(--border-subtle)",
          padding: "var(--s8) 0",
          marginBottom: "var(--s10)",
        }}
      >
        <div className="container">
          <div
            style={{
              display: "flex",
              gap: 8,
              marginBottom: 8,
              fontSize: 11,
              color: "var(--text-3)",
            }}
          >
            <Link href="/">Home</Link>
            <span>/</span>
            <span style={{ color: "var(--text-brand)" }}>Privacy Policy</span>
          </div>
          <h1
            style={{
              fontFamily: "var(--font-display)",
              fontSize: 32,
              fontWeight: 800,
              marginBottom: 8,
            }}
          >
            Privacy Policy
          </h1>
          <p style={{ fontSize: 12, color: "var(--text-3)" }}>Last updated: January 1, 2024</p>
        </div>
      </section>

      <section style={{ marginBottom: "var(--s16)" }}>
        <div className="container">
          <div
            style={{
              maxWidth: 760,
              margin: "0 auto",
              display: "flex",
              flexDirection: "column",
              gap: "var(--s8)",
            }}
          >
            {SECTIONS.map((section) => (
              <div key={section.title}>
                <h2
                  style={{
                    fontFamily: "var(--font-display)",
                    fontSize: 16,
                    fontWeight: 700,
                    marginBottom: 8,
                  }}
                >
                  {section.title}
                </h2>
                <p style={{ fontSize: 13, color: "var(--text-2)", lineHeight: 1.75 }}>
                  {section.body}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
